import { Poppins } from "next/font/google";
import "./globals.css";

// Load Poppins with weights you need (400 regular, 900 bold/italic if desired)
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "900"], // Include weights you're using
  variable: "--font-poppins", // Use as a CSS variable
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
